"""added role num for admin role and product rating logic.

Revision ID: 7b3b4a72d713
Revises: 2514cf066dc6
Create Date: 2026-08-19 13:20:11.866457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7b3b4a72d713'
down_revision: Union[str, Sequence[str], None] = '2514cf066dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.Column('comment_date', sa.DateTime(), nullable=False),
                    sa.Column('grade', sa.SmallInteger(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'product_id', name='idx_user_product_review')
                    )
    op.add_column('products', sa.Column('rating', sa.Float(), server_default=sa.text('0'), nullable=False))
    user_role_enum = sa.Enum('buyer', 'seller', 'admin', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('users', 'role',
                    existing_type=sa.VARCHAR(),
                    type_=user_role_enum,
                    existing_nullable=False,
                    postgresql_using="role::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.Enum('BUYER', 'SELLER', 'ADMIN', name='userrole'),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.drop_column('products', 'rating')
    op.drop_table('reviews')
    # ### end Alembic commands ###
