"""rename_review_unique_constraint

Revision ID: b21bad55e689
Revises: f935768f92b3
Create Date: 2026-08-21 11:48:33.019942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21bad55e689'
down_revision: Union[str, Sequence[str], None] = 'f935768f92b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('idx_user_product_review'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_user_product_review', 'reviews', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_product_review', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('idx_user_product_review'), 'reviews', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
